### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Kubuqi-Wu** [zolanaj/RemoteMicrogridOpt#1]
Hello！I'm sorry to bother you. Has the paper been published？Can I find it online

**Comment by zolanaj** [comment]
We should have a first look available soon, and I'll follow up once that's available.

**Comment by Kubuqi-Wu** [comment]
Thank you!

**Comment by zolanaj** [comment]
After a rather long proof process, the article is available here: 
https://doi.org/10.1287/ijoc.2020.0955

The readme has been updated accordingly.
